### ISSUE TITLE
Incorrect compat definition of NETDB_SUCCESS

### ISSUE THREAD

**Issue by smaeul** [OpenSMTPD/libasr#13]
On systems such as Linux with musl that do not define NETDB_SUCCESS, the definition from `openbsd-compat/defines.h` is used. This definition uses the wrong number, -1, which is defined immediately above to signify an internal error. OpenSMTPD [expects the value to be zero on success](https://github.com/OpenSMTPD/OpenSMTPD/blob/08d91c173f2338084f6a17198bf67ffb2e51774c/smtpd/dns.c#L355), which [matches the glibc definition](https://sourceware.org/git/?p=glibc.git;a=blob;f=resolv/netdb.h;h=f4eb1a7d60e2e8f0d0d0d95b367a441a43aae691;hb=HEAD#l74). As it is now, this causes all DNS lookups in OpenSMTPD to hit the failure case [here](https://github.com/OpenSMTPD/OpenSMTPD/blob/08d91c173f2338084f6a17198bf67ffb2e51774c/smtpd/dns.c#L364), and so mail fails to relay with `smtp-out: Failed to resolve MX for [relay:domain.tld]: Temporary failure in MX lookup`.

There is an appropriate patch [here](https://github.com/OpenSMTPD/libasr/pull/10/commits/95bfd14ed607aa6886460ce4d05073e4c67a5d2a) in #10

**Comment by ericfaurot** [comment]
Fixed, thanks!
