### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by KaneRoot** [OpenSMTPD/libasr#20]
Hello, I'm building packages for my operating system, and I could use a new release with the last modifications on the master branch.

Currently, I have an automake with version 0.16 and it's not working with the last release (but works fine with master).

Thanks!

**Comment by poolpOrg** [comment]
Hello,

I'll check with @ericfaurot if he has pending diffs and will keep you updated shortly

**Comment by ericfaurot** [comment]
I just released 1.0.3
