### ISSUE TITLE
libasr 1.0.3 lacks an explicit_bzero replacement function if it's missing

### ISSUE THREAD

**Issue by lquidfire** [OpenSMTPD/libasr#21]
I tried to built `opensmtpd 6.6.1p1` on CentOS 7, but it exited with the following error:

`...`
`checking for asr.h... yes`
`checking for asr_run in -lasr... no`
`configure: error: *** libasr missing - please install first or check config.log ***`

I had already successfuly built libasr 1.0.3 from git OpenSMTPD/libasr and added it to ldconfig by writing a config file `/etc/ld.so.conf.d/libasr.conf` with the following content: `/usr/local/lib/`; and then running `$ sudo ldconfig`.

`$ ldconfig -p | grep libasr` shows:
`libasr.so.0 (libc6,x86-64) => /usr/local/lib/libasr.so.0`
`libasr.so (libc6,x86-64) => /usr/local/lib/libasr.so`

Here is the [config.log](https://github.com/OpenSMTPD/libasr/files/3882865/config.log) from attempting the OpenSMTPd `./configure` step.

The error in there is: `.../builds/opensmtpd/conftest.c:133: undefined reference to `explicit_bzero'` on line 10988.

**Comment by poolpOrg** [comment]
Hello,

I have added a configure check for `explicit_bzero()` and added a replacement implementation in the library in case it is missing, can you give a git a try to latest git version ?

**Comment by lquidfire** [comment]
That fixed the issue, it seems. Thanks very much, Gilles!

`...`
`checking for asr.h... yes`
`checking for asr_run in -lasr... yes`

**Comment by poolpOrg** [comment]
great !
