### ISSUE TITLE
Off-by-one if the file ends without a newline

### ISSUE THREAD

**Issue by tamo** [OpenSMTPD/libasr#4]
Someone [says](https://twitter.com/tnozaki/status/560416056649334785) that asr.c has a mistake.

https://github.com/OpenSMTPD/libasr/blob/master/src/asr.c#L890

>CAVEATS
If the last line in a file does not contain a newline, the returned text won't contain a newline either.

http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man3/fgetln.3

**Comment by ericfaurot** [comment]
fixed in new release
