### ISSUE TITLE
build error on OS X: conflicting types for 'snprintf'

### ISSUE THREAD

**Issue by plavcik** [OpenSMTPD/libasr#9]
so far I used only OpenBSD version

today, I’m trying to compile OpenSMTPD cloned from git on OS X

Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64

instructions from README.md

during make, I ended with

Making all in openbsd-compat
gcc -DHAVE_CONFIG_H -I. -I..  -I../smtpd -I../openbsd-compat -I/opt/local -I/opt/local   -g -O2  -Qunused-arguments -Wunknown-warning-option -Wall -Wpointer-arith -Wuninitialized -Wsign-compare -Wformat-security -Wsizeof-pointer-memaccess -Wno-pointer-sign -Wno-unused-result -fno-strict-aliasing -fno-builtin-memset  -c -o arc4random.o arc4random.c
In file included from arc4random.c:27:
In file included from ./includes.h:77:
./openbsd-compat.h:152:5: warning: incompatible redeclaration of library function 'snprintf' [-Wincompatible-library-redeclaration]
int snprintf(char _, size_t, SNPRINTF_CONST char *, ...);
  ^
./openbsd-compat.h:152:5: note: 'snprintf' is a builtin with type 'int (char *, unsigned long, const char *, ...)'
1 warning generated.
gcc -DHAVE_CONFIG_H -I. -I..  -I../smtpd -I../openbsd-compat -I/opt/local -I/opt/local   -g -O2  -Qunused-arguments -Wunknown-warning-option -Wall -Wpointer-arith -Wuninitialized -Wsign-compare -Wformat-security -Wsizeof-pointer-memaccess -Wno-pointer-sign -Wno-unused-result -fno-strict-aliasing -fno-builtin-memset  -c -o base64.o base64.c
In file included from base64.c:47:
In file included from ./includes.h:77:
./openbsd-compat.h:152:5: warning: incompatible redeclaration of library function 'snprintf' [-Wincompatible-library-redeclaration]
int snprintf(char *, size_t, SNPRINTF_CONST char *, ...);
  ^
./openbsd-compat.h:152:5: note: 'snprintf' is a builtin with type 'int (char *, unsigned long, const char *, ...)'
In file included from base64.c:58:
/usr/include/stdio.h:421:6: error: conflicting types for 'snprintf'
int      snprintf(char \* __restrict, size_t, const char \* __restrict, ...) __printflike(3, 4);
       ^
./openbsd-compat.h:152:5: note: previous declaration is here
int snprintf(char *, size_t, SNPRINTF_CONST char *, ...);
  ^
1 warning and 1 error generated.
make[2]: *_\* [base64.o] Error 1
make[1]: **\* [all-recursive] Error 1
make: **\* [all] Error 2

**Comment by gnusosa** [comment]
I'm getting the same error.

```/Applications/Xcode-beta.app/Contents/Developer/usr/bin/make  all-recursive
Making all in openbsd-compat
gcc -DHAVE_CONFIG_H -I. -I..  -I../smtpd -I../openbsd-compat -I/usr/local/include -I/usr/local/opt/libressl//include   -g -O2  -Wall -Wpointer-arith -Wuninitialized -Wsign-compare -Wformat-security -Wsizeof-pointer-memaccess -Wno-pointer-sign -Wno-unused-result -fno-strict-aliasing -fno-builtin-memset  -c -o arc4random.o arc4random.c
gcc -DHAVE_CONFIG_H -I. -I..  -I../smtpd -I../openbsd-compat -I/usr/local/include -I/usr/local/opt/libressl//include   -g -O2  -Wall -Wpointer-arith -Wuninitialized -Wsign-compare -Wformat-security -Wsizeof-pointer-memaccess -Wno-pointer-sign -Wno-unused-result -fno-strict-aliasing -fno-builtin-memset  -c -o base64.o base64.c
In file included from base64.c:58:0:
/usr/include/stdio.h:421:6: error: conflicting types for 'snprintf'
 int  snprintf(char * __restrict, size_t, const char * __restrict, ...) __printflike(3, 4);
      ^
In file included from includes.h:77:0,
                 from base64.c:47:
openbsd-compat.h:152:5: note: previous declaration of 'snprintf' was here
 int snprintf(char *, size_t, SNPRINTF_CONST char *, ...);
     ^
make[2]: *** [base64.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by ericfaurot** [comment]
This is weird, it looks like snprintf was not detected properly in AC_CHECK_FUNCS.
Could you please show the config.log?

**Comment by poolpOrg** [comment]
I think Jung fixed something similar in smtpd recently FWIW
Le 22 janv. 2016 4:47 PM, Eric Faurot <notifications@github.com> a écrit :This is weird, it looks like snprintf was not detected properly in AC_CHECK_FUNCS.
Could you please show the config.log?

**Comment by gnusosa** [comment]
Most recent version works in El Capitan. Please close this issue.

As per my conversation with @ericfaurot, I downloaded the most recent version, and was able to build it successfully after pointing it to a OpenSSL libraries.

[config.log.txt](https://github.com/OpenSMTPD/libasr/files/101286/config.log.txt)
[config.verbose.output.log.txt](https://github.com/OpenSMTPD/libasr/files/101289/config.verbose.output.log.txt)

**Comment by ericfaurot** [comment]
Thanks for the update.
